apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature_converter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature_converter
  template:
    metadata:
      labels:
        app: temperature_converter
    spec:
      containers:
        - name: temperature_converter
          image: laxmiprasanna11/case_study:t2 # use your Docker Hub image
          ports:
            - containerPort: 5000
