apiVersion: v1
kind: Service
metadata:
  name: temperature-converter-service
spec:
  selector:
    app: temperature-converter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
